cpmmenting useless ones

diff --git a/.github/workflows/build-docs.yml b/.github/workflows/build-docs.yml
--- a/.github/workflows/build-docs.yml
+++ b/.github/workflows/build-docs.yml
@@ -1,51 +1,51 @@
-name: Build Lean documentation
-
-on:
-  workflow_dispatch:
-    inputs:
-      confirm:
-        description: "Type YES to rebuild Lean documentation"
-        required: true
-
-permissions:
-  contents: write
-
-jobs:
-  build-docs:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Confirm rebuild
-        run: |
-          if [ "${{ github.event.inputs.confirm }}" != "YES" ]; then
-            echo "Confirmation failed. Type YES to proceed."
-            exit 1
-          fi
-
-      - uses: actions/checkout@v4
-
-      - name: Install Lean
-        uses: leanprover/lean-action@v1
-
-      - name: Build Lean docs
-        run: |
-          cd docbuild
-          lake build GradCourse26:docs
-        #   export LAKE_NO_CACHE=1
-        #   mkdir -p docbuild
-        #   MATHLIB_NO_CACHE_ON_UPDATE=1 lake update doc-gen4
-
-# For debugging purposes
-      - name: Locate generated docs
-        run: |
-                echo "Searching for index.html"
-                find . -path "*build/doc/index.html"
-
-      - name: Commit generated docs
-        run: |
-          git config user.name "github-actions"
-          git config user.email "github-actions@github.com"
-
-          git add docbuild/.lake/build/doc
-          git commit -m "Update Lean documentation" || echo "No changes to commit"
-          git push
+# name: Build Lean documentation
+# 
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       confirm:
+#         description: "Type YES to rebuild Lean documentation"
+#         required: true
+# 
+# permissions:
+#   contents: write
+# 
+# jobs:
+#   build-docs:
+#     runs-on: ubuntu-latest
+# 
+#     steps:
+#       - name: Confirm rebuild
+#         run: |
+#           if [ "${{ github.event.inputs.confirm }}" != "YES" ]; then
+#             echo "Confirmation failed. Type YES to proceed."
+#             exit 1
+#           fi
+# 
+#       - uses: actions/checkout@v4
+# 
+#       - name: Install Lean
+#         uses: leanprover/lean-action@v1
+# 
+#       - name: Build Lean docs
+#         run: |
+#           cd docbuild
+#           lake build GradCourse26:docs
+#         #   export LAKE_NO_CACHE=1
+#         #   mkdir -p docbuild
+#         #   MATHLIB_NO_CACHE_ON_UPDATE=1 lake update doc-gen4
+# 
+# # For debugging purposes
+#       - name: Locate generated docs
+#         run: |
+#                 echo "Searching for index.html"
+#                 find . -path "*build/doc/index.html"
+# 
+#       - name: Commit generated docs
+#         run: |
+#           git config user.name "github-actions"
+#           git config user.email "github-actions@github.com"
+# 
+#           git add docbuild/.lake/build/doc
+#           git commit -m "Update Lean documentation" || echo "No changes to commit"
+#           git push
